### PR TITLE
fix: error build on Swift 5.10

### PR DESCRIPTION
**Pull request by jwthanh**
- break a long expression into smaller expressions
- fix the error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

When my team upgraded to XCode 15.3 (Swift 5.10). they got the error

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/bazelpods/Sources/BazelPodsCore/Core/MultiPlatform.swift:108:16: error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
        return .functionCall(name: "select", arguments: [.basic((
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: fatalError
Target @bazelpods//:bazelpods failed to build
```

I followed this stuff https://sarunw.com/posts/how-to-fix-the-compiler-is-unable-to-type-check-this-expression-in-reasonable-time/ and broke the long-expression to smaller.

### CODE REVIEW

**Comment by sergeykhliustin** [comment]
@jwthanh thanks for your fix!
Released: https://github.com/sergeykhliustin/BazelPods/releases/tag/1.11.5
